// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using NighTrain.Sample.Data.Context;

namespace NighTrain.Sample.Data.Migrations
{
    [DbContext(typeof(NighTrainContext))]
    partial class NighTrainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NighTrain.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(2021, 3, 28, 14, 1, 27, 529, DateTimeKind.Local).AddTicks(3391),
                            Name = "Name",
                            Surname = "Surname"
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(2021, 3, 28, 14, 1, 27, 530, DateTimeKind.Local).AddTicks(1367),
                            Name = "Name2",
                            Surname = "Surname2"
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateTime(2021, 3, 28, 14, 1, 27, 530, DateTimeKind.Local).AddTicks(1382),
                            Name = "Name3",
                            Surname = "Surname3"
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateTime(2021, 3, 28, 14, 1, 27, 530, DateTimeKind.Local).AddTicks(1384),
                            Name = "Name4",
                            Surname = "Surname4"
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateTime(2021, 3, 28, 14, 1, 27, 530, DateTimeKind.Local).AddTicks(1385),
                            Name = "Name5",
                            Surname = "Surname5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
